swagger: '2.0'
info:
  title: Fetch-BulkPayment-Details-From-FTP
  x-ibm-name: fetch-bulkpayment-deatils-from-ftp
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - operation-switch:
          version: 2.0.0
          title: operation-switch
          case:
            - operations:
                - verb: get
                  path: /fetchfilefromFTP
              execute:
                - xslt:
                    version: 2.0.0
                    title: xslt
                    input: false
                    source: |-
                      <xsl:stylesheet exclude-result-prefixes="dp" extension-element-prefixes="dp" xmlns:dp="http://www.datapower.com/extensions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
                      <xsl:template match="/">
                      <xsl:variable name="sftp-put-url"
                         select="'sftp://bandaru:sarasu10@192.168.2.50/home/bandaru/Documents/suresh.xml'"/>
                      <dp:url-open target="{$sftp-put-url}">
                        <xsl:copy-of select="/"/>
                      </dp:url-open>
                      </xsl:template>
                      </xsl:stylesheet>
                    serialize-output: true
                - parse:
                    version: 2.1.0
                    title: parse
                    parse-settings-reference:
                      default: apic-default-parsesettings
            - operations:
                - verb: get
                  path: /insertintoDB
              execute:
                - xslt:
                    version: 2.0.0
                    title: Reading File From Database
                    input: false
                    source: "<xsl:stylesheet exclude-result-prefixes=\"dp\" extension-element-prefixes=\"dp\" xmlns:dp=\"http://www.datapower.com/extensions\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" version=\"1.0\">\r\n\r\n\r\n<xsl:template match=\"/\">\r\n\r\n\r\n<xsl:variable name=\"ftp-put-url\"\r\n   select=\"'ftp://user:user@192.168.0.136/test/Bulk_Payment_Customer_Transaction_Details.xml'\"/>\r\n<dp:url-open target=\"{$ftp-put-url}\">\r\n  <xsl:copy-of select=\"/\"/>\r\n</dp:url-open>\r\n\r\n</xsl:template>\r\n\r\n</xsl:stylesheet>"
                    serialize-output: true
                - parse:
                    version: 2.1.0
                    title: parse
                    parse-settings-reference:
                      default: apic-default-parsesettings
                - xslt:
                    version: 2.0.0
                    title: Inserting into Database
                    input: true
                    source: "<xsl:stylesheet version=\"1.0\"\r\nxmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" xmlns:dp=\"http://www.datapower.com/extensions\" xmlns:apim=\"http://www.ibm.com/apimanagement\"\r\nextension-element-prefixes=\"dp apim\">\r\n<xsl:output indent=\"yes\" encoding=\"UTF-8\" version=\"1.0\" method=\"xml\"/>\r\n \r\n<xsl:template match=\"//bulk_payments\">\r\n   \r\n\r\n<xsl:for-each  select=\"customer\">\r\n\r\n\r\n    <xsl:variable name=\"name\">\r\n\r\n<xsl:value-of select=\"name\" />\r\n\r\n</xsl:variable>\r\n\r\n\r\n\r\n<xsl:variable name=\"account_number\">\r\n\r\n<xsl:value-of select=\"account_number\" />\r\n\r\n</xsl:variable>\r\n<xsl:for-each  select=\"transaction\">\r\n\r\n\r\n<xsl:variable name=\"id\">\r\n\r\n<xsl:value-of select=\"id\" />\r\n\r\n</xsl:variable>\r\n\r\n\r\n<xsl:variable name=\"beneficiary_name\">\r\n\r\n<xsl:value-of select=\"beneficiary_name\" />\r\n\r\n</xsl:variable>\r\n\r\n<xsl:variable name=\"beneficiary_account\">\r\n\r\n<xsl:value-of select=\"beneficiary_account\" />\r\n\r\n</xsl:variable>\r\n\r\n<xsl:variable name=\"amount\">\r\n\r\n<xsl:value-of select=\"amount\" />\r\n\r\n</xsl:variable>\r\n\r\n<xsl:variable name=\"currency\">\r\n\r\n<xsl:value-of select=\"currency\" />\r\n\r\n</xsl:variable>\r\n\r\n<xsl:variable name=\"description\">\r\n\r\n<xsl:value-of select=\"description\" />\r\n\r\n</xsl:variable>\r\n\r\n<xsl:variable name=\"number\" select=\"//customer[count(*)]\"/>\r\n <xsl:message dp:prioriry=\"error\"><xsl:value-of select=\"$number\"/></xsl:message>\r\n\r\n\r\n  <dp:sql-execute source=\"'S_SQL'\" statement=\"'insert into Bulk_Payments values(?,?,?,?,?,?,?,?)'\">\r\n    <arguments>\r\n      <argument type=\"SQL_VARCHAR\" mode=\"INPUT\">\r\n        <xsl:value-of select=\"$id\"/>\r\n      </argument>\r\n      <argument type=\"SQL_VARCHAR\" mode=\"INPUT\">\r\n        <xsl:value-of select=\"$name\"/>\r\n      </argument>\r\n\t  <argument type=\"SQL_VARCHAR\" mode=\"INPUT\">\r\n        <xsl:value-of select=\"$account_number\"/>\r\n      </argument>\r\n\t  <argument type=\"SQL_VARCHAR\" mode=\"INPUT\">\r\n        <xsl:value-of select=\"$beneficiary_name\"/>\r\n      </argument>\r\n <argument type=\"SQL_VARCHAR\" mode=\"INPUT\">\r\n        <xsl:value-of select=\"$beneficiary_account\"/>\r\n      </argument>\r\n      <argument type=\"SQL_VARCHAR\" mode=\"INPUT\">\r\n        <xsl:value-of select=\"$amount\"/>\r\n      </argument>\r\n\t  <argument type=\"SQL_VARCHAR\" mode=\"INPUT\">\r\n        <xsl:value-of select=\"$currency\"/>\r\n      </argument>\r\n\t  <argument type=\"SQL_VARCHAR\" mode=\"INPUT\">\r\n        <xsl:value-of select=\"$description\"/>\r\n      </argument>\t \r\n    </arguments>\r\n  </dp:sql-execute>\r\n </xsl:for-each>\r\n </xsl:for-each>\r\n</xsl:template>\r\n</xsl:stylesheet>"
                    serialize-output: false
                - xslt:
                    version: 2.0.0
                    title: Success Response
                    input: false
                    source: "<xsl:stylesheet version=\"1.0\" xmlns:apigw=\"http://www.ibm.com/xmlns/datapower/2017/11/apigateway\"  xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" extension-element-prefixes=\"apigw\">\r\n    <xsl:output indent=\"yes\"  version=\"1.0\" method=\"xml\"/>\r\n <xsl:template match=\"/\">\r\n    <apigw:set-header name=\"'Content-Type'\" value=\"'application/xml'\"/>\r\n     <xsl:copy>\r\n         <output>\r\n        <status>\r\n    File Read from Remote Location\r\n            and\r\n    Inserted into Database.\r\n    Please check respective Database!!\r\n       </status>\r\n    </output>\r\n     </xsl:copy>\r\n  </xsl:template>\r\n</xsl:stylesheet>"
                    serialize-output: true
          otherwise: []
    finally: []
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
  servers:
    - url: ''
  oauth-servers: []
basePath: /fileread-ftp
paths:
  /insertintoDB:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
    parameters: []
  /fetchfilefromFTP:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
