swagger: '2.0'
info:
  title: JoseModule
  x-ibm-name: josemodule
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: >-
            var jose=require('jose');

            var jwk=require('jwk');

            var jsonpaylaod='This is your Json input';

            var jsonString=JSON.stringify(jsonpaylaod);

            // Read public cert and convert as JWK

            var publicjwk = {};

            publicjwk= jwk.readCertificate('APIC_V10');// public cert alias
            created in Datapower

            var hdr = jose.createJWSHeader("APIC_V10", 'RS256'); //private key
            alias from Datapower

            hdr.setProtected("jwk",publicjwk);

            var mySign = jose.createJWSSigner(hdr);

            mySign.update(jsonString);

            mySign.sign('json_flat',function(error, jwsstring)

            {


            if (error) {

            session.output.write("error: "+error);

            } else {


            context.message.body.write(jwsstring);

            }

            });
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /josemodule
paths:
  /JOSE:
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
    parameters:
      - name: Payload
        required: true
        in: body
        schema:
          $ref: '#/definitions/Request'
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
definitions:
  Request:
    type: object
    example:
      ACCOUNT_NUMBER: '6545215454'
      NAME: VAMSI
      IFSC: EDK08
      BALANCE: '8500'
      BRANCH: PEDDAPURAM
